sudo: false
language: python
python:
        - 2.7
        # Remove 3.5 because SpiNNMan isn't Py3-compatible yet
        # - 3.5
before_install:
        - pip install --upgrade pip setuptools wheel
        - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNUtils.git@${TRAVIS_BRANCH} || pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNUtils.git@master
        - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNMachine.git@${TRAVIS_BRANCH} || pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNMachine.git@master
        - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git@${TRAVIS_BRANCH} || pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git@master
        - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNMan.git@${TRAVIS_BRANCH} || pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNMan.git@master
install:
        - python setup.py develop
        - pip install -r requirements-test.txt
        - pip install python-coveralls
script:
        - >
            py.test tests/ \
                    --cov spalloc_server \
                    --cov tests \
                    --durations=10
        # Code quality check
        - flake8
after_success:
        - coveralls
notifications:
        email: false

matrix:
    fast_finish: true
