language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
cache: pip
addons:
  apt:
    packages:
      - openjdk-8-jre-headless
      - ant

before_install:
  # Work around ludicrous Travis bug
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  - support/rat.sh download
  # Bring pip up to date 
  - pip install --upgrade pip setuptools wheel
  # SpiNNakerManchester internal dependencies; development mode
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNUtils.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMachine.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMan.git
install:
  - python setup.py develop
  - pip install -r requirements-test.txt
  - pip install python-coveralls 'coverage>=4.4'
script:
  - py.test tests/ --cov spalloc_server --durations=10
  # Code quality check
  - flake8
  # Copyright check
  - support/rat.sh run
after_success:
  - coveralls

notifications:
  email: false
