# Copyright (c) 2017-2019 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
cache: pip
addons:
  apt:
    packages:
      - openjdk-8-jre-headless
      - ant

before_install:
  # Work around ludicrous Travis bug
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  - support/rat.sh download
  # Bring pip up to date 
  - pip install --upgrade pip setuptools wheel
  # SpiNNakerManchester internal dependencies; development mode
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNUtils.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMachine.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMan.git
install:
  - python setup.py develop
  - pip install -r requirements-test.txt
  - pip install pylint python-coveralls 'coverage>=4.4,<5.0'
script:
  - py.test tests/ --cov spalloc_server --durations=10
  # Code quality check
  - flake8
  - ( pylint --output-format=colorized --disable=R,C spalloc_server; exit $(($? & 35)) )
  # Copyright check
  - support/rat.sh run
after_success:
  - coveralls

notifications:
  email: false
